// <auto-generated />
using Api.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Persistencia.Migraciones
{
    [DbContext(typeof(AplicacionDbContext))]
    [Migration("20240628123331_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Aplicacion.Dominio.Domicilio", b =>
                {
                    b.Property<string>("Calle")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Altura")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.HasKey("Calle");

                    b.ToTable("Domicilio");

                    b.HasData(
                        new
                        {
                            Calle = "Domicilio1",
                            Altura = 1,
                            CodigoPostal = 1
                        },
                        new
                        {
                            Calle = "Domicilio2",
                            Altura = 2,
                            CodigoPostal = 2
                        });
                });

            modelBuilder.Entity("Aplicacion.Dominio.Usuario", b =>
                {
                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Direccion");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Direccion = "Dirección1",
                            Apellido = "ApellidoA",
                            Nombre = "Usuario1"
                        },
                        new
                        {
                            Direccion = "Dirección2",
                            Apellido = "ApellidoB",
                            Nombre = "Usuario2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
